pipeline {
    agent any
    stages {
        stage('hello') {
            steps {
                echo "welcome to jenkins...."
                sh 'whoami'
                sh 'pwd'
              }
          }
      }
  }
